### ISSUE TITLE
population statistics: datatiede 2017-18 has suspicious graphs

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#466] opened 2018-10-03 17:59 UTC
![image](https://user-images.githubusercontent.com/523235/46429446-201e4a80-c74f-11e8-891b-be99a21cfafb.png)

**Comment by sasumaki** [comment] 2018-10-04 07:19
Because of Oodis' faulty `is_leaf` feature. e.g. here the problem is that Bachelor of Science is marked as a course before 2008.
Temporal fix: check if course has at least one `is_leaf: false` study attainment if true mark it as study module.

**Closed** 2018-10-09 13:28 UTC
Labels: back, bug, front
