### ISSUE TITLE
Look into fixing duplicate teachers

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone2-frontend#691] opened 2019-02-18 12:12 UTC
all teachers have duplicates. The duplicates have the number 9 in front of their ID.
We should figure out how to fix this situation of the duplicates. The teacher IDs are different lengths so simply adding or removing number 9 to the front of the ID may be difficult because we need to correctly identify which is a dupe ID and which is not and we may accidentally select real teachers.

![image](https://user-images.githubusercontent.com/468816/52965057-97761300-33ac-11e9-8cf3-02517782cde5.png)

**Comment by ikuisma** [comment] 2019-02-21 08:27
Duplicate of #650

**Closed** 2019-02-26 20:39 UTC
Labels: back, bug
